const CORS_HEADERS = {
    'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Agent-ID, X-Trigger-Type, X-SoulOS-Key',
        };

        function corsJSON(data, status = 200) {
          return new Response(JSON.stringify(data, null, 2), {
              status,
                  headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
                    });
                    }

                    export default {
                      async fetch(request, env, ctx) {
                          if (request.method === 'OPTIONS') {
                                return new Response(null, { status: 204, headers: CORS_HEADERS });
                                    }

                                        const url = new URL(request.url);
                                            const path = url.pathname;

                                                if (path === '/' && request.method === 'GET') {
                                                      return corsJSON({
                                                              gateway: 'soul-os-api',
                                                                      domain: 'api.soul-os.cc',
                                                                              status: 'operational',
                                                                                      version: '2.0.0',
                                                                                              description: 'Constellation API Gateway',
                                                                                                      upstream: 'siddartha (service binding)',
                                                                                                              routes: {
                                                                                                                        'GET  /': 'This manifest',
                                                                                                                                  'GET  /health': 'Gateway + upstream health',
                                                                                                                                            'GET  /waypoints': 'Siddhartha waypoint registry',
                                                                                                                                                      'GET  /mailbox/:agent': 'Siddhartha agent mailbox',
                                                                                                                                                                'POST /v1/chat/completions': 'Siddhartha OpenAI-compatible chat',
                                                                                                                                                                          'POST /api/route': 'Siddhartha memory-hydrated agent call',
                                                                                                                                                                                    'POST /dispatch': 'Siddhartha passage dispatch',
                                                                                                                                                                                              'POST /message': 'Siddhartha inter-agent message',
                                                                                                                                                                                                        'POST /chain': 'Siddhartha multi-hop chain',
                                                                                                                                                                                                                  'POST /parietal': 'Siddhartha semantic gravity',
                                                                                                                                                                                                                            'POST /log': 'Siddhartha atlas session log',
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                  if (path === '/health' && request.method === 'GET') {
                                                                                                                                                                                                                                                        let upstream = { ok: false, error: 'not checked' };
                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                      if (env.SIDDARTHA) {
                                                                                                                                                                                                                                                                                const upstreamReq = new Request('https://siddartha.internal/health', { method: 'GET' });
                                                                                                                                                                                                                                                                                          const res = await env.SIDDARTHA.fetch(upstreamReq);
                                                                                                                                                                                                                                                                                                    upstream = await res.json();
                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                      upstream = { ok: false, error: 'SIDDARTHA service binding not configured' };
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                            upstream = { ok: false, error: e.message };
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                        return corsJSON({
                                                                                                                                                                                                                                                                                                                                                                ok: true,
                                                                                                                                                                                                                                                                                                                                                                        service: 'soul-os-api',
                                                                                                                                                                                                                                                                                                                                                                                version: '2.0.0',
                                                                                                                                                                                                                                                                                                                                                                                        ts: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                upstream,
                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              if (!env.SIDDARTHA) {
                                                                                                                                                                                                                                                                                                                                                                                                                    return corsJSON({
                                                                                                                                                                                                                                                                                                                                                                                                                            error: 'SIDDARTHA service binding not configured',
                                                                                                                                                                                                                                                                                                                                                                                                                                    hint: 'Add a service binding named SIDDARTHA pointing to the siddartha worker',
                                                                                                                                                                                                                                                                                                                                                                                                                                          }, 503);
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const proxyUrl = new URL(request.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              proxyUrl.hostname = 'siddartha.internal';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const proxyReq = new Request(proxyUrl.toString(), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            method: request.method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: request.headers,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            body: request.method !== 'GET' && request.method !== 'HEAD' ? request.body : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const response = await env.SIDDARTHA.fetch(proxyReq);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const headers = new Headers(response.headers);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Object.entries(CORS_HEADERS).forEach(([k, v]) => headers.set(k, v));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return new Response(response.body, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: response.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          statusText: response.statusText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return corsJSON({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error: 'Upstream error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message: e.message,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  method: request.method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 502);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
